[continue]
name = "Continue"
description = "Continue writing"
prompt = ''

[summarize-text]
name = "Summarize Text"
description = "Summarize a text document"
prompt = '''
Summarize text:
'''

[three-sentence-summary]
name = "Three Sentence Summary"
description = "Summarize a text document into three sentences"
prompt = '''
Summarize text into three sentences:
'''

[write-introduction]
name = "Write Introduction"
description = "Write an introduction for a text document"
prompt = '''
Write an introduction for the following text:
'''

[write-conclusion]
name = "Write Conclusion"
description = "Write a conclusion for a text document"
prompt = '''
Write a conclusion for the following text:
'''

[create-outline]
name = "Create Outline"
description = "Create an outline from text"
prompt = '''
Create outline from text:
'''

[extract-keywords]
name = "Extract Keywords"
description = "Extract keywords from text"
prompt = '''
Extract keywords from text:
'''

[extract-entities]
name = "Extract Entities"
description = "Extract entities from a text"
prompt = '''
Extract entities from text:
'''

[brainstorm-ideas]
name = "Brainstorm Ideas"
description = "Brainstorm ideas using text"
prompt = '''
Brainstorm ideas using the following text:
'''

[ask-questions]
name = "Ask Questions"
description = "Ask questions from text"
prompt = '''
Ask questions about the following text:
'''

[common-objections]
name = "Common Objections"
description = "Find common objections to your idea"
prompt = '''
Find common objections to the following idea:
'''

[find-contradictions]
name = "Find Contradictions"
description = "Find contradictions in text"
prompt = '''
Find contradictions in the following text:
'''

[define]
name = "Define"
description = "Define a word"
prompt = '''Define a word: '''

[find-synonyms]
name = "Find Synonyms"
description = "Find synonyms for a word"
prompt = '''Find synonyms for a word: '''

[find-antonyms]
name = "Find Antonyms"
description = "Find antonyms for a word"
prompt = '''Find antonyms for a word: '''

[find-related-words]
name = "Find Related Words"
description = "Find related words for a word"
prompt = '''Find related words for a word: '''

[markdown-table]
name = "Markdown Table"
description = "Create a markdown table"
prompt = '''
Create a markdown table using the following text:
'''

[find-quotes]
name = "Find Quotes"
description = "Find quotes in text"
prompt = '''
Find quotes in the following text:

'''
[convert-links-to-markdown]
name = "Convert Links to Markdown"
description = "Convert links to markdown"
prompt = '''
Convert links in the following text to markdown:
'''

[most-important-ideas]
name = "Most Important Ideas"
description = "Find the most important ideas in text"
prompt = '''
Find the most important ideas in the following text:
'''

[write-blog-post]
name = "Write Blog Post"
description = "Write a blog post about topic"
prompt = '''
Write a blog post about the following text:
'''

[write-tweet]
name = "Write Tweet"
description = "Write a tweet in less than 280 characters about the following topic:"
prompt = '''
Write a tweet about:
'''

[fix-grammar]
name = "Fix Grammar"
description = "Fix grammar in text"
prompt = '''
Fix grammar in the following text:
'''

[fix-spelling]
name = "Fix Spelling"
description = "Fix spelling in text"
prompt = '''
Fix spelling in the following text:
'''

[csv-output]
name = "CSV Export"
description = "CSV file for"
prompt = '''
Give me in a CSV format: 
'''


[pros-cons]
name = "Pros and Cons Table"
description = "Pros and Cons Table"
prompt = '''
Give me Pros and Cons in a table for: 
'''

[translate-to-english]
name = "Translate to English"
description = "Translate text to English"
prompt = '''
Translate text to English:
'''

[translate-to-chinese]
name = "Translate to Chinese"
description = "Translate text to Chinese"
prompt = '''
Translate text to Chinese:
'''

[translate-to-spanish]
name = "Translate to Spanish"
description = "Translate text to Spanish"
prompt = '''
Translate text to Spanish:
'''

[translate-to-german]
name = "Translate to German"
description = "Translate text to German"
prompt = '''
Translate text to German:
'''

[translate-to-french]
name = "Translate to French"
description = "Translate text to French"
prompt = '''
Translate text to French:
'''

[translate-to-italian]
name = "Translate to Italian"
description = "Translate text to Italian"
prompt = '''
Translate text to Italian:
'''

[translate-to-japanese]
name = "Translate to Japanese"
description = "Translate text to Japanese"
prompt = '''
Translate text to Japanese:
'''

[translate-to-korean]
name = "Translate to Korean"
description = "Translate text to Korean"
prompt = '''
Translate text to Korean:
'''

[translate-to-portuguese]
name = "Translate to Portuguese"
description = "Translate text to Portuguese"
prompt = '''
Translate text to Portuguese:
'''

[translate-to-russian]
name = "Translate to Russian"
description = "Translate text to Russian"
prompt = '''
Translate text to Russian:
'''

[translate-to-arabic]
name = "Translate to Arabic"
description = "Translate text to Arabic"
prompt = '''
Translate text to Arabic:
'''

[translate-to-hindi]
name = "Translate to Hindi"
description = "Translate text to Hindi"
prompt = '''
Translate text to Hindi:
'''
